### ISSUE TITLE
Starterpaket für lokale/regionale Chapter

### ISSUE THREAD

**Issue by nuest** [DE-RSE/chapter#10]
## Inhalte Starterpaket

- T-Shirts (max. 5) für die Organisatoren
- Slide-Deck (Markdown-basiert? Google Slides?) für Slide-Karaoke über Verein und Community
- Sticker
- Budget für Getränke / Snacks (Auslagenerstattung auf Beleg, max. 100 €)
- [Link Ideenliste erstes Treffen]

Die Vorstandsmitglieder sind auch offen "vorbei zu kommen", aber natürlich können wir das nicht garantieren. Zögert aber nicht, eine Anfrage zu stellen.

------

_Feedback Willkommen!_

**Comment by nuest** [comment]
Wird in nächster Vorstandssitzung besprochen.

**Comment by knarrff** [comment]
Finde ich generell gut. Eine Idee wäre noch, das an Konditionen zu binden (Blogpost, ...)

**Comment by nuest** [comment]
Wird im Vorstand diskutiert.
