### ISSUE TITLE
Add The Turing Way Community Handbook to the list of resources

### ISSUE THREAD

**Issue by nuest** [DE-RSE/chapter#20]
https://the-turing-way.netlify.app/community-handbook/community-handbook.html is mostly The Turing Way's own way of running things, but has great approaches and ideas on managing events, newsletter, calls, doing acknowledgement etc. that are relevant to building a community

**Comment by MakisH** [comment]
Not sure why this issue is in this repository (probably a lot has changed since 2021), but we now have a nice collection of learning and teaching resources: https://de-rse.org/learn-and-teach/

I added this resource there: https://github.com/DE-RSE/learn-and-teach/pull/28
