### ISSUE TITLE
Create Chapter Website

### ISSUE THREAD

**Issue by HeidiSeibold** [DE-RSE/chapter#3]
What needs to be done to create a chapter website?

**Comment by sdruskat** [comment]
Suggestion:

1. [ ] The board decides that we want to offer chapters to host their websites on GitHub pages under the [de-RSE](https://github.com/de-rse) org. To be done at the next board meeting.
2. [ ] We decide if we want to have a specific path for these pages (probably a bad idea, better use the GH pages mechanism of putting project pages in a slug, e.g., de-rse.org/rse-munich) or a specific naming convention (e.g., rse-{place}, although this may break cool custom names?!?)
3. [ ] Chapters apply in issues in this repo for a repository in the de-rse org, and name an admin.
4. [ ] Chapters run the website themselves.

@nuest @HeidiSeibold What do you think?

**Comment by nuest** [comment]
Website is online at https://de-rse.org/chapter/

Some content is missing, but the "process" to set up a chapter is documented: https://de-rse.org/chapter/start/
